### ISSUE TITLE
The `--version` flag is broken

### ISSUE THREAD

**Issue by HakierGrzonzo** [jmlopez-rod/m#72]
Hello!

When installing from pypi, the newest version of m outputs `0.0.0-PLACEHOLDER` when run with `--version` flag.

```
$ m --version
0.0.0-PLACEHOLDER
```

**Comment by jmlopez-rod** [comment]
This may be happening because the script may be loading your local python `m` package. Everything that is published to pypi removes that string via `sed` substitution:

https://github.com/jmlopez-rod/m/blob/master/m/scripts/build/pypi.sh#L24
